baseURL: https://heal.lgbt/
title: Queer Healing Resources
theme: book
publishDir: docs/
googleAnalytics: UA-125560-7
languageCode: en-us
enableEmoji: true
disableKinds: ['taxonomy', 'taxonomyTerm']
params:
    BookToC: 3
    description: heal.lgbt is a website dedicated to LGBTQIA+ healing, coming out, mental health, physical and mental health, self-care and community care, personal growth, and allyship.
